import type { Task } from './types';

export const mockTasks: Task[] = [
    {
        id: '1',
        title: 'Настроить окружение проекта',
        description: 'Инициализировать Vite, TypeScript и структуру FSD',
        priority: 'high',
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    },
    {
        id: '2',
        title: 'Сверстать страницу задач',
        description: 'Список задач и фильтр по приоритету',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    },
    {
        id: '3',
        title: 'Добавить модалку создания задачи',
        priority: 'high',
        createdAt: Date.now() - 1000 * 60 * 60 * 24,
    },
    {
        id: '4',
        title: 'Написать README',
        description: 'Описать структуру и запуск проекта',
        priority: 'low',
        createdAt: Date.now() - 1000 * 60 * 60 * 5,
    },
    {
        id: '5',
        title: 'Проверить типы и линтер',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 30,
    },
    {
        id: '6',
        title: 'Добавить фильтрацию по приоритету',
        description: 'Реализовать выбор приоритета и отображение подходящих задач',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 60 * 4,
    },
    {
        id: '7',
        title: 'Добавить удаление задачи',
        description: 'Реализовать удаление задачи из списка',
        priority: 'high',
        createdAt: Date.now() - 1000 * 60 * 60 * 6,
    },
    {
        id: '8',
        title: 'Добавить редактирование задачи',
        description: 'Позволить изменять название, описание и приоритет',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 60 * 8,
    },
    {
        id: '9',
        title: 'Сделать адаптивную верстку',
        description: 'Проверить отображение приложения на мобильных устройствах',
        priority: 'high',
        createdAt: Date.now() - 1000 * 60 * 60 * 10,
    },
    {
        id: '10',
        title: 'Добавить пустое состояние',
        description: 'Показать сообщение, если список задач пуст',
        priority: 'low',
        createdAt: Date.now() - 1000 * 60 * 60 * 12,
    },
    {
        id: '11',
        title: 'Улучшить валидацию формы',
        description: 'Добавить проверку длины названия и описания задачи',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 60 * 15,
    },
    {
        id: '12',
        title: 'Добавить подтверждение удаления',
        description: 'Показывать модальное окно перед удалением задачи',
        priority: 'low',
        createdAt: Date.now() - 1000 * 60 * 60 * 18,
    },
    {
        id: '13',
        title: 'Оптимизировать список задач',
        description: 'Проверить лишние перерисовки компонентов списка',
        priority: 'high',
        createdAt: Date.now() - 1000 * 60 * 60 * 20,
    },
    {
        id: '14',
        title: 'Добавить сортировку задач',
        description: 'Сортировать задачи по дате создания и приоритету',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 60 * 24,
    },
    {
        id: '15',
        title: 'Добавить кнопку очистки фильтра',
        description: 'Позволить быстро сбрасывать выбранный фильтр',
        priority: 'low',
        createdAt: Date.now() - 1000 * 60 * 60 * 27,
    },
    {
        id: '16',
        title: 'Проверить работу модальных окон',
        description: 'Убедиться, что модалки корректно открываются и закрываются',
        priority: 'high',
        createdAt: Date.now() - 1000 * 60 * 60 * 30,
    },
    {
        id: '17',
        title: 'Добавить закрытие модалки по Escape',
        description: 'Закрывать активную модалку при нажатии клавиши Escape',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 60 * 32,
    },
    {
        id: '18',
        title: 'Добавить блокировку скролла',
        description: 'Запретить прокрутку страницы при открытой модалке',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 60 * 36,
    },
    {
        id: '19',
        title: 'Проверить доступность формы',
        description: 'Добавить корректные label, focus-состояния и aria-атрибуты',
        priority: 'high',
        createdAt: Date.now() - 1000 * 60 * 60 * 40,
    },
    {
        id: '20',
        title: 'Добавить состояние загрузки',
        description: 'Показать индикатор загрузки при выполнении операций',
        priority: 'low',
        createdAt: Date.now() - 1000 * 60 * 60 * 44,
    },
    {
        id: '21',
        title: 'Добавить уведомления',
        description: 'Показывать сообщение после создания или удаления задачи',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 60 * 48,
    },
    {
        id: '22',
        title: 'Настроить сохранение задач',
        description: 'Сохранять список задач в localStorage',
        priority: 'high',
        createdAt: Date.now() - 1000 * 60 * 60 * 52,
    },
    {
        id: '23',
        title: 'Добавить восстановление задач',
        description: 'Загружать сохраненные задачи при старте приложения',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 60 * 56,
    },
    {
        id: '24',
        title: 'Проверить работу на разных браузерах',
        description: 'Протестировать приложение в Chrome, Firefox и Safari',
        priority: 'low',
        createdAt: Date.now() - 1000 * 60 * 60 * 60,
    },
    {
        id: '25',
        title: 'Провести финальный рефакторинг',
        description: 'Удалить дублирование кода и привести компоненты к единому стилю',
        priority: 'medium',
        createdAt: Date.now() - 1000 * 60 * 60 * 72,
    },
];
